#ifndef L1TRC_TrcMod_DEF_H
#define L1TRC_TrcMod_DEF_H

	#include "L1Trc.h"

	#include "dhl_l1_trace.h"
	#include "edata_path_trace.h"
	#include "edata_path_detail_trace.h"
	#include "erlcul_trace.h"
	#include "erlcul_detail_trace.h"
	#include "erlcdl_trace.h"
	#include "erlcdl_detail_trace.h"
	#include "emac_trace.h"
	#include "emac_detail_trace.h"
	#include "epdcp_trace.h"
	#include "epdcp_detail_trace.h"
	#include "data_path.h"
	#include "data_path_detail.h"
	#include "qmu_bm_trace.h"
	#include "rohc_trace.h"
	#include "rohc_detail_trace.h"
	#include "ral_trace.h"
	#include "ral_detail_trace.h"
	#include "hif_drv_data_path_trace.h"
	#include "hif_mw_data_path_trace.h"
	#include "hif_srv_data_path_trace.h"
	#include "UL1D_Pcore_Trace.h"
	#include "UL1C_Pcore_Trace.h"
	#include "gl1_pcore_trace.h"
	#include "l1audio_trace.h"
	#include "lte_l2_trace.h"
	#include "el1d_trace_rf.h"
	#include "mmrf_pcore_trace.h"
	#include "PCORE_DCXO_DIV_Trace1.h"
	#include "PCORE_OSTD_Trace1.h"
	#include "PCORE_PTP_Trace1.h"
	#include "PCORE_SleepDrv_Trace1.h"
	#include "PCORE_MD_TOPSM_Trace1.h"
	#include "PCORE_DVFS_Trace1.h"
	#include "PCORE_TPPA_SleepDrv_Trace1.h"

#endif
