/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*****************************************************************************
 *
 * Filename:
 * ---------
 *   e1l_custom_nvram_def.c
 *
 * Project:
 * --------
 *   MT6291
 *
 * Description:
 * ------------
 *    
 * Author:
 * -------
 * -------
 *
 *==============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * removed!
 * removed!
 * removed!
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *============================================================================
 *------------------------------------------------------------------------------*/
#ifndef NVRAM_NOT_PRESENT

/*
 *   Include Headers
 */

#include "kal_general_types.h"
#include "kal_public_api.h"
#include "kal_public_defs.h"
/*
 *   NVRAM Basic Headers
 */
#ifdef NVRAM_AUTO_GEN
//#include "nvram_auto_gen.h"
#endif

#include "nvram_enums.h"
#include "nvram_defs.h"
#include "nvram_data_items.h"

/*
 *   User Headers
 */
#include "el1_custom_nvram_def.h"
#include "el1d_rf_custom_data.h"
#include "el1d_rf_drdi.h"
#include "el1d_rf_cid.h"

extern void nvram_get_eL1_mipi_ant_value_to_write(nvram_lid_el1_custom_enum lid_el1_custom, kal_uint8 *buffer_el1_custom, kal_uint16 buffer_size);
/*
 *   Default value
 */
/* EL1_MIPI_ANT LIDs' default values are left in nvram_el1def.c */ 


//LID declaration
ltable_entry_struct logical_data_item_table_el1_custom[] =
{

   {
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_0THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV01",
      VER(NVRAM_EF_EL1_MIPI_ANTRX_EVENT_0THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_1STBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV02",
      VER(NVRAM_EF_EL1_MIPI_ANTRX_EVENT_1STBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_2NDBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV03",
      VER(NVRAM_EF_EL1_MIPI_ANTRX_EVENT_2NDBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_3RDBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV04",
      VER(NVRAM_EF_EL1_MIPI_ANTRX_EVENT_3RDBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_4THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV05",
      VER(NVRAM_EF_EL1_MIPI_ANTRX_EVENT_4THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_5THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV06",
      VER(NVRAM_EF_EL1_MIPI_ANTRX_EVENT_5THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_6THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV07",
      VER(NVRAM_EF_EL1_MIPI_ANTRX_EVENT_6THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_7THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV08",
      VER(NVRAM_EF_EL1_MIPI_ANTRX_EVENT_7THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_8THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV09",
      VER(NVRAM_EF_EL1_MIPI_ANTRX_EVENT_8THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_9THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV0A",
      VER(NVRAM_EF_EL1_MIPI_ANTRX_EVENT_9THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_10THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV0B",
      VER(NVRAM_EF_EL1_MIPI_ANTRX_EVENT_10THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_11THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV0C",
      VER(NVRAM_EF_EL1_MIPI_ANTRX_EVENT_11THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_12THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV0D",
      VER(NVRAM_EF_EL1_MIPI_ANTRX_EVENT_12THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_13THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV0E",
      VER(NVRAM_EF_EL1_MIPI_ANTRX_EVENT_13THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_14THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV0F",
      VER(NVRAM_EF_EL1_MIPI_ANTRX_EVENT_14THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_15THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV0G",
      VER(NVRAM_EF_EL1_MIPI_ANTRX_EVENT_15THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_16THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV0H",
      VER(NVRAM_EF_EL1_MIPI_ANTRX_EVENT_16THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_17THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV0I",
      VER(NVRAM_EF_EL1_MIPI_ANTRX_EVENT_17THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_18THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV0J",
      VER(NVRAM_EF_EL1_MIPI_ANTRX_EVENT_18THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_19THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV0K",
      VER(NVRAM_EF_EL1_MIPI_ANTRX_EVENT_19THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_20THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTRX_EVENT_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV0L",
      VER(NVRAM_EF_EL1_MIPI_ANTRX_EVENT_20THBAND_LID)
   },

   {  // TX_EVENT_0THBAND
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_0THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV10",
      VER(NVRAM_EF_EL1_MIPI_ANTTX_EVENT_0THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_1STBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV11",
      VER(NVRAM_EF_EL1_MIPI_ANTTX_EVENT_1STBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_2NDBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV12",
      VER(NVRAM_EF_EL1_MIPI_ANTTX_EVENT_2NDBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_3RDBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV13",
      VER(NVRAM_EF_EL1_MIPI_ANTTX_EVENT_3RDBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_4THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV14",
      VER(NVRAM_EF_EL1_MIPI_ANTTX_EVENT_4THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_5THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV15",
      VER(NVRAM_EF_EL1_MIPI_ANTTX_EVENT_5THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_6THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV16",
      VER(NVRAM_EF_EL1_MIPI_ANTTX_EVENT_6THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_7THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV17",
      VER(NVRAM_EF_EL1_MIPI_ANTTX_EVENT_7THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_8THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV18",
      VER(NVRAM_EF_EL1_MIPI_ANTTX_EVENT_8THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_9THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV19",
      VER(NVRAM_EF_EL1_MIPI_ANTTX_EVENT_9THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_10THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV1A",
      VER(NVRAM_EF_EL1_MIPI_ANTTX_EVENT_10THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_11THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV1B",
      VER(NVRAM_EF_EL1_MIPI_ANTTX_EVENT_11THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_12THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV1C",
      VER(NVRAM_EF_EL1_MIPI_ANTTX_EVENT_12THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_13THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV1D",
      VER(NVRAM_EF_EL1_MIPI_ANTTX_EVENT_13THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_14THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV1E",
      VER(NVRAM_EF_EL1_MIPI_ANTTX_EVENT_14THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_15THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV1F",
      VER(NVRAM_EF_EL1_MIPI_ANTTX_EVENT_15THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_16THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV1G",
      VER(NVRAM_EF_EL1_MIPI_ANTTX_EVENT_16THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_17THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV1H",
      VER(NVRAM_EF_EL1_MIPI_ANTTX_EVENT_17THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_18THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV1I",
      VER(NVRAM_EF_EL1_MIPI_ANTTX_EVENT_18THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_19THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV1J",
      VER(NVRAM_EF_EL1_MIPI_ANTTX_EVENT_19THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_20THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTTX_EVENT_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV1K",
      VER(NVRAM_EF_EL1_MIPI_ANTTX_EVENT_20THBAND_LID)
   },

   {  
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_0THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV20",//??
      VER(NVRAM_EF_EL1_MIPI_ANTRX_DATA_0THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_1STBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV21",
      VER(NVRAM_EF_EL1_MIPI_ANTRX_DATA_1STBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_2NDBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV22",
      VER(NVRAM_EF_EL1_MIPI_ANTRX_DATA_2NDBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_3RDBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV23",
      VER(NVRAM_EF_EL1_MIPI_ANTRX_DATA_3RDBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_4THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV24",
      VER(NVRAM_EF_EL1_MIPI_ANTRX_DATA_4THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_5THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV25",
      VER(NVRAM_EF_EL1_MIPI_ANTRX_DATA_5THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_6THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV26",
      VER(NVRAM_EF_EL1_MIPI_ANTRX_DATA_6THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_7THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV27",
      VER(NVRAM_EF_EL1_MIPI_ANTRX_DATA_7THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_8THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV28",
      VER(NVRAM_EF_EL1_MIPI_ANTRX_DATA_8THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_9THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV29",
      VER(NVRAM_EF_EL1_MIPI_ANTRX_DATA_9THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_10THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV2A",
      VER(NVRAM_EF_EL1_MIPI_ANTRX_DATA_10THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_11THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV2B",
      VER(NVRAM_EF_EL1_MIPI_ANTRX_DATA_11THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_12THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV2C",
      VER(NVRAM_EF_EL1_MIPI_ANTRX_DATA_12THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_13THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV2D",
      VER(NVRAM_EF_EL1_MIPI_ANTRX_DATA_13THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_14THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV2E",
      VER(NVRAM_EF_EL1_MIPI_ANTRX_DATA_14THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_15THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV2F",
      VER(NVRAM_EF_EL1_MIPI_ANTRX_DATA_15THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_16THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV2G",
      VER(NVRAM_EF_EL1_MIPI_ANTRX_DATA_16THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_17THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV2H",
      VER(NVRAM_EF_EL1_MIPI_ANTRX_DATA_17THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_18THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV2I",
      VER(NVRAM_EF_EL1_MIPI_ANTRX_DATA_18THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_19THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV2J",
      VER(NVRAM_EF_EL1_MIPI_ANTRX_DATA_19THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_20THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTRX_DATA_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV2K",
      VER(NVRAM_EF_EL1_MIPI_ANTRX_DATA_20THBAND_LID)
   },

   {  
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_0THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV30",
      VER(NVRAM_EF_EL1_MIPI_ANTTX_DATA_0THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_1STBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV31",
      VER(NVRAM_EF_EL1_MIPI_ANTTX_DATA_1STBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_2NDBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV32",
      VER(NVRAM_EF_EL1_MIPI_ANTTX_DATA_2NDBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_3RDBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV33",
      VER(NVRAM_EF_EL1_MIPI_ANTTX_DATA_3RDBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_4THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV34",
      VER(NVRAM_EF_EL1_MIPI_ANTTX_DATA_4THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_5THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV35",
      VER(NVRAM_EF_EL1_MIPI_ANTTX_DATA_5THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_6THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV36",
      VER(NVRAM_EF_EL1_MIPI_ANTTX_DATA_6THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_7THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV37",
      VER(NVRAM_EF_EL1_MIPI_ANTTX_DATA_7THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_8THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV38",
      VER(NVRAM_EF_EL1_MIPI_ANTTX_DATA_8THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_9THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV39",
      VER(NVRAM_EF_EL1_MIPI_ANTTX_DATA_9THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_10THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV3A",
      VER(NVRAM_EF_EL1_MIPI_ANTTX_DATA_10THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_11THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV3B",
      VER(NVRAM_EF_EL1_MIPI_ANTTX_DATA_11THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_12THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV3C",
      VER(NVRAM_EF_EL1_MIPI_ANTTX_DATA_12THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_13THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV3D",
      VER(NVRAM_EF_EL1_MIPI_ANTTX_DATA_13THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_14THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV3E",
      VER(NVRAM_EF_EL1_MIPI_ANTTX_DATA_14THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_15THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV3F",
      VER(NVRAM_EF_EL1_MIPI_ANTTX_DATA_15THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_16THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV3G",
      VER(NVRAM_EF_EL1_MIPI_ANTTX_DATA_16THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_17THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV3H",
      VER(NVRAM_EF_EL1_MIPI_ANTTX_DATA_17THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_18THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV3I",
      VER(NVRAM_EF_EL1_MIPI_ANTTX_DATA_18THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_19THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV3J",
      VER(NVRAM_EF_EL1_MIPI_ANTTX_DATA_19THBAND_LID)
   },

   {
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_20THBAND_LID,
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_TOTAL,
      NVRAM_EF_EL1_MIPI_ANTTX_DATA_SIZE,
      NVRAM_DEFAULT_FUNC(nvram_get_eL1_mipi_ant_value_to_write),
      NVRAM_CATEGORY_CALIBRAT | NVRAM_CATEGORY_FUNC_DEFAULT,
      NVRAM_ATTR_MULTIPLE,
      "AV3K",
      VER(NVRAM_EF_EL1_MIPI_ANTTX_DATA_20THBAND_LID)
    },
};


#endif /* NVRAM_NOT_PRESENT */
