/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   el1_custom_nvram_def.h
 *
 * Project:
 * --------
 *   MT6291
 *
 * Description:
 * ------------
 *    
 * Author:
 * -------
 * -------
 *
 *==============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * removed!
 * removed!
 * removed!
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *============================================================================
 *******************************************************************************/

#ifndef __EL1_CUSTOM_NVRAM_DEF_H__
#define __EL1_CUSTOM_NVRAM_DEF_H__

#ifdef __cplusplus
extern "C"
{
#endif /* __cplusplus */

/*
 *   Include Headers
 */
 

/*
 *   NVRAM Basic Headers
 */
#include "nvram_data_items.h"



/*
 *   User Headers
 */
 
 


/*
 *   LID Enums
 */
 
//el1_custom LID enum
typedef enum
{
        NVRAM_EF_EL1_MIPI_ANTRX_EVENT_START       = NVRAM_LID_GRP_EL1_CUSTOM(0),
        NVRAM_EF_EL1_MIPI_ANTRX_EVENT_0THBAND_LID = NVRAM_EF_EL1_MIPI_ANTRX_EVENT_START,
        NVRAM_EF_EL1_MIPI_ANTRX_EVENT_1STBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(1),
        NVRAM_EF_EL1_MIPI_ANTRX_EVENT_2NDBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(2),
        NVRAM_EF_EL1_MIPI_ANTRX_EVENT_3RDBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(3),
        NVRAM_EF_EL1_MIPI_ANTRX_EVENT_4THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(4),
        NVRAM_EF_EL1_MIPI_ANTRX_EVENT_5THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(5),
        NVRAM_EF_EL1_MIPI_ANTRX_EVENT_6THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(6),
        NVRAM_EF_EL1_MIPI_ANTRX_EVENT_7THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(7),
        NVRAM_EF_EL1_MIPI_ANTRX_EVENT_8THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(8),
        NVRAM_EF_EL1_MIPI_ANTRX_EVENT_9THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(9),
        NVRAM_EF_EL1_MIPI_ANTRX_EVENT_10THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(10),
        NVRAM_EF_EL1_MIPI_ANTRX_EVENT_11THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(11),
        NVRAM_EF_EL1_MIPI_ANTRX_EVENT_12THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(12),
        NVRAM_EF_EL1_MIPI_ANTRX_EVENT_13THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(13),
        NVRAM_EF_EL1_MIPI_ANTRX_EVENT_14THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(14),
        NVRAM_EF_EL1_MIPI_ANTRX_EVENT_15THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(15),
        NVRAM_EF_EL1_MIPI_ANTRX_EVENT_16THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(16),
        NVRAM_EF_EL1_MIPI_ANTRX_EVENT_17THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(17),
        NVRAM_EF_EL1_MIPI_ANTRX_EVENT_18THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(18),
        NVRAM_EF_EL1_MIPI_ANTRX_EVENT_19THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(19),
        NVRAM_EF_EL1_MIPI_ANTRX_EVENT_20THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(20),
        NVRAM_EF_EL1_MIPI_ANTRX_EVENT_END = NVRAM_EF_EL1_MIPI_ANTRX_EVENT_20THBAND_LID,

        NVRAM_EF_EL1_MIPI_ANTTX_EVENT_START        = NVRAM_LID_GRP_EL1_CUSTOM(21),
        NVRAM_EF_EL1_MIPI_ANTTX_EVENT_0THBAND_LID = NVRAM_EF_EL1_MIPI_ANTTX_EVENT_START,
        NVRAM_EF_EL1_MIPI_ANTTX_EVENT_1STBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(22),
        NVRAM_EF_EL1_MIPI_ANTTX_EVENT_2NDBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(23),
        NVRAM_EF_EL1_MIPI_ANTTX_EVENT_3RDBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(24),
        NVRAM_EF_EL1_MIPI_ANTTX_EVENT_4THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(25),
        NVRAM_EF_EL1_MIPI_ANTTX_EVENT_5THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(26),
        NVRAM_EF_EL1_MIPI_ANTTX_EVENT_6THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(27),
        NVRAM_EF_EL1_MIPI_ANTTX_EVENT_7THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(28),
        NVRAM_EF_EL1_MIPI_ANTTX_EVENT_8THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(29),
        NVRAM_EF_EL1_MIPI_ANTTX_EVENT_9THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(30),
        NVRAM_EF_EL1_MIPI_ANTTX_EVENT_10THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(31),
        NVRAM_EF_EL1_MIPI_ANTTX_EVENT_11THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(32),
        NVRAM_EF_EL1_MIPI_ANTTX_EVENT_12THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(33),
        NVRAM_EF_EL1_MIPI_ANTTX_EVENT_13THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(34),
        NVRAM_EF_EL1_MIPI_ANTTX_EVENT_14THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(35),
        NVRAM_EF_EL1_MIPI_ANTTX_EVENT_15THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(36),
        NVRAM_EF_EL1_MIPI_ANTTX_EVENT_16THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(37),
        NVRAM_EF_EL1_MIPI_ANTTX_EVENT_17THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(38),
        NVRAM_EF_EL1_MIPI_ANTTX_EVENT_18THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(39),
        NVRAM_EF_EL1_MIPI_ANTTX_EVENT_19THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(40),
        NVRAM_EF_EL1_MIPI_ANTTX_EVENT_20THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(41),
        NVRAM_EF_EL1_MIPI_ANTTX_EVENT_END = NVRAM_EF_EL1_MIPI_ANTTX_EVENT_20THBAND_LID,

        NVRAM_EF_EL1_MIPI_ANTRX_DATA_START         = NVRAM_LID_GRP_EL1_CUSTOM(42),
        NVRAM_EF_EL1_MIPI_ANTRX_DATA_0THBAND_LID = NVRAM_EF_EL1_MIPI_ANTRX_DATA_START,
        NVRAM_EF_EL1_MIPI_ANTRX_DATA_1STBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(43),
        NVRAM_EF_EL1_MIPI_ANTRX_DATA_2NDBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(44),
        NVRAM_EF_EL1_MIPI_ANTRX_DATA_3RDBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(45),
        NVRAM_EF_EL1_MIPI_ANTRX_DATA_4THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(46),
        NVRAM_EF_EL1_MIPI_ANTRX_DATA_5THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(47),
        NVRAM_EF_EL1_MIPI_ANTRX_DATA_6THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(48),
        NVRAM_EF_EL1_MIPI_ANTRX_DATA_7THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(49),
        NVRAM_EF_EL1_MIPI_ANTRX_DATA_8THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(50),
        NVRAM_EF_EL1_MIPI_ANTRX_DATA_9THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(51),
        NVRAM_EF_EL1_MIPI_ANTRX_DATA_10THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(52),
        NVRAM_EF_EL1_MIPI_ANTRX_DATA_11THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(53),
        NVRAM_EF_EL1_MIPI_ANTRX_DATA_12THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(54),
        NVRAM_EF_EL1_MIPI_ANTRX_DATA_13THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(55),
        NVRAM_EF_EL1_MIPI_ANTRX_DATA_14THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(56),
        NVRAM_EF_EL1_MIPI_ANTRX_DATA_15THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(57),
        NVRAM_EF_EL1_MIPI_ANTRX_DATA_16THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(58),
        NVRAM_EF_EL1_MIPI_ANTRX_DATA_17THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(59),
        NVRAM_EF_EL1_MIPI_ANTRX_DATA_18THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(60),
        NVRAM_EF_EL1_MIPI_ANTRX_DATA_19THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(61),
        NVRAM_EF_EL1_MIPI_ANTRX_DATA_20THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(62),
        NVRAM_EF_EL1_MIPI_ANTRX_DATA_END = NVRAM_EF_EL1_MIPI_ANTRX_DATA_20THBAND_LID,

        NVRAM_EF_EL1_MIPI_ANTTX_DATA_START        = NVRAM_LID_GRP_EL1_CUSTOM(63),
        NVRAM_EF_EL1_MIPI_ANTTX_DATA_0THBAND_LID = NVRAM_EF_EL1_MIPI_ANTTX_DATA_START,
        NVRAM_EF_EL1_MIPI_ANTTX_DATA_1STBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(64),
        NVRAM_EF_EL1_MIPI_ANTTX_DATA_2NDBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(65),
        NVRAM_EF_EL1_MIPI_ANTTX_DATA_3RDBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(66),
        NVRAM_EF_EL1_MIPI_ANTTX_DATA_4THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(67),
        NVRAM_EF_EL1_MIPI_ANTTX_DATA_5THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(68),
        NVRAM_EF_EL1_MIPI_ANTTX_DATA_6THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(69),
        NVRAM_EF_EL1_MIPI_ANTTX_DATA_7THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(70),
        NVRAM_EF_EL1_MIPI_ANTTX_DATA_8THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(71),
        NVRAM_EF_EL1_MIPI_ANTTX_DATA_9THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(72),
        NVRAM_EF_EL1_MIPI_ANTTX_DATA_10THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(73),
        NVRAM_EF_EL1_MIPI_ANTTX_DATA_11THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(74),
        NVRAM_EF_EL1_MIPI_ANTTX_DATA_12THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(75),
        NVRAM_EF_EL1_MIPI_ANTTX_DATA_13THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(76),
        NVRAM_EF_EL1_MIPI_ANTTX_DATA_14THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(77),
        NVRAM_EF_EL1_MIPI_ANTTX_DATA_15THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(78),
        NVRAM_EF_EL1_MIPI_ANTTX_DATA_16THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(79),
        NVRAM_EF_EL1_MIPI_ANTTX_DATA_17THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(80),
        NVRAM_EF_EL1_MIPI_ANTTX_DATA_18THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(81),
        NVRAM_EF_EL1_MIPI_ANTTX_DATA_19THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(82),
        NVRAM_EF_EL1_MIPI_ANTTX_DATA_20THBAND_LID = NVRAM_LID_GRP_EL1_CUSTOM(83),
        NVRAM_EF_EL1_MIPI_ANTTX_DATA_END = NVRAM_EF_EL1_MIPI_ANTTX_DATA_20THBAND_LID,

        NVRAM_EF_EL1_MIPI_ANT_LAST_LID                        = NVRAM_LID_GRP_EL1_CUSTOM(255)
}nvram_lid_el1_custom_enum;

//Verno
#define NVRAM_EF_EL1_MIPI_ANTRX_EVENT_0THBAND_LID_VERNO                   "000"
#define NVRAM_EF_EL1_MIPI_ANTRX_EVENT_1STBAND_LID_VERNO                   "000"
#define NVRAM_EF_EL1_MIPI_ANTRX_EVENT_2NDBAND_LID_VERNO                   "000"
#define NVRAM_EF_EL1_MIPI_ANTRX_EVENT_3RDBAND_LID_VERNO                   "000"
#define NVRAM_EF_EL1_MIPI_ANTRX_EVENT_4THBAND_LID_VERNO                   "000"
#define NVRAM_EF_EL1_MIPI_ANTRX_EVENT_5THBAND_LID_VERNO                   "000"
#define NVRAM_EF_EL1_MIPI_ANTRX_EVENT_6THBAND_LID_VERNO                   "000"
#define NVRAM_EF_EL1_MIPI_ANTRX_EVENT_7THBAND_LID_VERNO                   "000"
#define NVRAM_EF_EL1_MIPI_ANTRX_EVENT_8THBAND_LID_VERNO                   "000"
#define NVRAM_EF_EL1_MIPI_ANTRX_EVENT_9THBAND_LID_VERNO                   "000"
#define NVRAM_EF_EL1_MIPI_ANTRX_EVENT_10THBAND_LID_VERNO                  "000"
#define NVRAM_EF_EL1_MIPI_ANTRX_EVENT_11THBAND_LID_VERNO                  "000"
#define NVRAM_EF_EL1_MIPI_ANTRX_EVENT_12THBAND_LID_VERNO                  "000"
#define NVRAM_EF_EL1_MIPI_ANTRX_EVENT_13THBAND_LID_VERNO                  "000"
#define NVRAM_EF_EL1_MIPI_ANTRX_EVENT_14THBAND_LID_VERNO                  "000"
#define NVRAM_EF_EL1_MIPI_ANTRX_EVENT_15THBAND_LID_VERNO                  "000"
#define NVRAM_EF_EL1_MIPI_ANTRX_EVENT_16THBAND_LID_VERNO                  "000"
#define NVRAM_EF_EL1_MIPI_ANTRX_EVENT_17THBAND_LID_VERNO                  "000"
#define NVRAM_EF_EL1_MIPI_ANTRX_EVENT_18THBAND_LID_VERNO                  "000"
#define NVRAM_EF_EL1_MIPI_ANTRX_EVENT_19THBAND_LID_VERNO                  "000"
#define NVRAM_EF_EL1_MIPI_ANTRX_EVENT_20THBAND_LID_VERNO                  "000"

#define NVRAM_EF_EL1_MIPI_ANTTX_EVENT_0THBAND_LID_VERNO                   "000"
#define NVRAM_EF_EL1_MIPI_ANTTX_EVENT_1STBAND_LID_VERNO                   "000"
#define NVRAM_EF_EL1_MIPI_ANTTX_EVENT_2NDBAND_LID_VERNO                   "000"
#define NVRAM_EF_EL1_MIPI_ANTTX_EVENT_3RDBAND_LID_VERNO                   "000"
#define NVRAM_EF_EL1_MIPI_ANTTX_EVENT_4THBAND_LID_VERNO                   "000"
#define NVRAM_EF_EL1_MIPI_ANTTX_EVENT_5THBAND_LID_VERNO                   "000"
#define NVRAM_EF_EL1_MIPI_ANTTX_EVENT_6THBAND_LID_VERNO                   "000"
#define NVRAM_EF_EL1_MIPI_ANTTX_EVENT_7THBAND_LID_VERNO                   "000"
#define NVRAM_EF_EL1_MIPI_ANTTX_EVENT_8THBAND_LID_VERNO                   "000"
#define NVRAM_EF_EL1_MIPI_ANTTX_EVENT_9THBAND_LID_VERNO                   "000"
#define NVRAM_EF_EL1_MIPI_ANTTX_EVENT_10THBAND_LID_VERNO                  "000"
#define NVRAM_EF_EL1_MIPI_ANTTX_EVENT_11THBAND_LID_VERNO                  "000"
#define NVRAM_EF_EL1_MIPI_ANTTX_EVENT_12THBAND_LID_VERNO                  "000"
#define NVRAM_EF_EL1_MIPI_ANTTX_EVENT_13THBAND_LID_VERNO                  "000"
#define NVRAM_EF_EL1_MIPI_ANTTX_EVENT_14THBAND_LID_VERNO                  "000"
#define NVRAM_EF_EL1_MIPI_ANTTX_EVENT_15THBAND_LID_VERNO                  "000"
#define NVRAM_EF_EL1_MIPI_ANTTX_EVENT_16THBAND_LID_VERNO                  "000"
#define NVRAM_EF_EL1_MIPI_ANTTX_EVENT_17THBAND_LID_VERNO                  "000"
#define NVRAM_EF_EL1_MIPI_ANTTX_EVENT_18THBAND_LID_VERNO                  "000"
#define NVRAM_EF_EL1_MIPI_ANTTX_EVENT_19THBAND_LID_VERNO                  "000"
#define NVRAM_EF_EL1_MIPI_ANTTX_EVENT_20THBAND_LID_VERNO                  "000"

#define NVRAM_EF_EL1_MIPI_ANTRX_DATA_0THBAND_LID_VERNO                    "000"
#define NVRAM_EF_EL1_MIPI_ANTRX_DATA_1STBAND_LID_VERNO                    "000"
#define NVRAM_EF_EL1_MIPI_ANTRX_DATA_2NDBAND_LID_VERNO                    "000"
#define NVRAM_EF_EL1_MIPI_ANTRX_DATA_3RDBAND_LID_VERNO                    "000"
#define NVRAM_EF_EL1_MIPI_ANTRX_DATA_4THBAND_LID_VERNO                    "000"
#define NVRAM_EF_EL1_MIPI_ANTRX_DATA_5THBAND_LID_VERNO                    "000"
#define NVRAM_EF_EL1_MIPI_ANTRX_DATA_6THBAND_LID_VERNO                    "000"
#define NVRAM_EF_EL1_MIPI_ANTRX_DATA_7THBAND_LID_VERNO                    "000"
#define NVRAM_EF_EL1_MIPI_ANTRX_DATA_8THBAND_LID_VERNO                    "000"
#define NVRAM_EF_EL1_MIPI_ANTRX_DATA_9THBAND_LID_VERNO                    "000"
#define NVRAM_EF_EL1_MIPI_ANTRX_DATA_10THBAND_LID_VERNO                   "000"
#define NVRAM_EF_EL1_MIPI_ANTRX_DATA_11THBAND_LID_VERNO                   "000"
#define NVRAM_EF_EL1_MIPI_ANTRX_DATA_12THBAND_LID_VERNO                   "000"
#define NVRAM_EF_EL1_MIPI_ANTRX_DATA_13THBAND_LID_VERNO                   "000"
#define NVRAM_EF_EL1_MIPI_ANTRX_DATA_14THBAND_LID_VERNO                   "000"
#define NVRAM_EF_EL1_MIPI_ANTRX_DATA_15THBAND_LID_VERNO                   "000"
#define NVRAM_EF_EL1_MIPI_ANTRX_DATA_16THBAND_LID_VERNO                   "000"
#define NVRAM_EF_EL1_MIPI_ANTRX_DATA_17THBAND_LID_VERNO                   "000"
#define NVRAM_EF_EL1_MIPI_ANTRX_DATA_18THBAND_LID_VERNO                   "000"
#define NVRAM_EF_EL1_MIPI_ANTRX_DATA_19THBAND_LID_VERNO                   "000"
#define NVRAM_EF_EL1_MIPI_ANTRX_DATA_20THBAND_LID_VERNO                   "000"

#define NVRAM_EF_EL1_MIPI_ANTTX_DATA_0THBAND_LID_VERNO                    "000"
#define NVRAM_EF_EL1_MIPI_ANTTX_DATA_1STBAND_LID_VERNO                    "000"
#define NVRAM_EF_EL1_MIPI_ANTTX_DATA_2NDBAND_LID_VERNO                    "000"
#define NVRAM_EF_EL1_MIPI_ANTTX_DATA_3RDBAND_LID_VERNO                    "000"
#define NVRAM_EF_EL1_MIPI_ANTTX_DATA_4THBAND_LID_VERNO                    "000"
#define NVRAM_EF_EL1_MIPI_ANTTX_DATA_5THBAND_LID_VERNO                    "000"
#define NVRAM_EF_EL1_MIPI_ANTTX_DATA_6THBAND_LID_VERNO                    "000"
#define NVRAM_EF_EL1_MIPI_ANTTX_DATA_7THBAND_LID_VERNO                    "000"
#define NVRAM_EF_EL1_MIPI_ANTTX_DATA_8THBAND_LID_VERNO                    "000"
#define NVRAM_EF_EL1_MIPI_ANTTX_DATA_9THBAND_LID_VERNO                    "000"
#define NVRAM_EF_EL1_MIPI_ANTTX_DATA_10THBAND_LID_VERNO                   "000"
#define NVRAM_EF_EL1_MIPI_ANTTX_DATA_11THBAND_LID_VERNO                   "000"
#define NVRAM_EF_EL1_MIPI_ANTTX_DATA_12THBAND_LID_VERNO                   "000"
#define NVRAM_EF_EL1_MIPI_ANTTX_DATA_13THBAND_LID_VERNO                   "000"
#define NVRAM_EF_EL1_MIPI_ANTTX_DATA_14THBAND_LID_VERNO                   "000"
#define NVRAM_EF_EL1_MIPI_ANTTX_DATA_15THBAND_LID_VERNO                   "000"
#define NVRAM_EF_EL1_MIPI_ANTTX_DATA_16THBAND_LID_VERNO                   "000"
#define NVRAM_EF_EL1_MIPI_ANTTX_DATA_17THBAND_LID_VERNO                   "000"
#define NVRAM_EF_EL1_MIPI_ANTTX_DATA_18THBAND_LID_VERNO                   "000"
#define NVRAM_EF_EL1_MIPI_ANTTX_DATA_19THBAND_LID_VERNO                   "000"
#define NVRAM_EF_EL1_MIPI_ANTTX_DATA_20THBAND_LID_VERNO                   "000"

//structure of each LID
typedef struct
{
   LTE_MIPI_EVENT_TABLE_T mipi_antrx_event[LTE_MIPI_ANT_EVENT_NUM];
}nvram_el1_mipi_antrx_event_struct;

typedef struct
{
   LTE_MIPI_EVENT_TABLE_T mipi_anttx_event[LTE_MIPI_ANT_EVENT_NUM];
}nvram_el1_mipi_anttx_event_struct;

typedef struct
{
   LTE_MIPI_DATA_SUBBAND_TABLE_T mipi_antrx_data[LTE_MIPI_ANT_DATA_NUM];
}nvram_el1_mipi_antrx_data_struct;

typedef struct
{
   LTE_MIPI_DATA_SUBBAND_TABLE_T mipi_anttx_data[LTE_MIPI_ANT_DATA_NUM];
}nvram_el1_mipi_anttx_data_struct;

//Size and total
#define NVRAM_EF_EL1_MIPI_ANTRX_EVENT_SIZE               (sizeof(LTE_MIPI_EVENT_TABLE_T)*LTE_MIPI_ANT_EVENT_NUM)
#define NVRAM_EF_EL1_MIPI_ANTRX_EVENT_TOTAL               1

#define NVRAM_EF_EL1_MIPI_ANTTX_EVENT_SIZE               (sizeof(LTE_MIPI_EVENT_TABLE_T)*LTE_MIPI_ANT_EVENT_NUM)
#define NVRAM_EF_EL1_MIPI_ANTTX_EVENT_TOTAL               1

#define NVRAM_EF_EL1_MIPI_ANTRX_DATA_SIZE                (sizeof(LTE_MIPI_DATA_SUBBAND_TABLE_T)*LTE_MIPI_ANT_DATA_NUM)
#define NVRAM_EF_EL1_MIPI_ANTRX_DATA_TOTAL                1

#define NVRAM_EF_EL1_MIPI_ANTTX_DATA_SIZE                (sizeof(LTE_MIPI_DATA_SUBBAND_TABLE_T)*LTE_MIPI_ANT_DATA_NUM)
#define NVRAM_EF_EL1_MIPI_ANTTX_DATA_TOTAL                1


#ifdef __cplusplus
}
#endif

#endif /* NVRAM_DATA_ITEMS_H */ /* define NVRAM_DATA_ITEMS_H */
