/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2015
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*****************************************************************************
 *
 * Filename:
 * ---------
 *     dcl_pmic6353_sw.h
 *
 * Project:
 * --------
 *     MOLY Software
 *
 * Description:
 * ------------
 *     This file is for PMIC 6353
 *
 * Author:
 * -------
 * -------
 *
 *============================================================================
 * HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 *
 * removed!
 * removed!
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *============================================================================
 ****************************************************************************/

#ifndef __DCL_PMIC6353_SW_H_STRUCT__
#define __DCL_PMIC6353_SW_H_STRUCT__

#include "dcl_pmic_features.h"

#ifdef PMIC_6353_REG_API

// Combinational functions
extern void pmic6353_customization_init(void);

typedef enum
{
    MT6353_HWCID,
    MT6353_SWCID,
    MT6353_RG_SPK_CCODE,
    MT6353_RG_SPK_EN_VIEW_VCM,
    MT6353_RG_SPK_FBRC_EN,
    MT6353_SPK_TEST_MODE0,
    MT6353_SPK_TD_DONE,
    MT6353_RG_VPA_ZX_OS_TRIM,
    MT6353_BUCK_VS1_VOSEL,
    MT6353_BUCK_VS1_VOSEL_ON,
    MT6353_BUCK_VCORE_EN_CTRL,
    MT6353_BUCK_VCORE_VOSEL_CTRL,
    MT6353_BUCK_VCORE_EN,
    MT6353_DA_NI_VCORE_VOSEL,
    MT6353_BUCK_VCORE_VOSEL,
    MT6353_BUCK_VCORE_VOSEL_ON,
    MT6353_BUCK_VCORE_VOSEL_SLEEP,
    MT6353_BUCK_VCORE2_EN_CTRL,
    MT6353_BUCK_VCORE2_VOSEL_CTRL,
    MT6353_BUCK_VCORE2_EN,
    MT6353_DA_NI_VCORE2_VOSEL,
    MT6353_BUCK_VCORE2_VOSEL,
    MT6353_BUCK_VCORE2_VOSEL_ON,
    MT6353_BUCK_VCORE2_VOSEL_SLEEP,
    MT6353_BUCK_VPA_EN,
    MT6353_BUCK_VPA_VOSEL,
    MT6353_LDO_VTCXO24_SWITCH,
    MT6353_LDO_VTCXO28_LP_MODE,
    MT6353_LDO_VTCXO28_EN,
    MT6353_LDO_VTCXO28_LP_CTRL,
    MT6353_LDO_VTCXO28_EN_CTRL,
    MT6353_LDO_VTCXO28_LP_SEL,
    MT6353_LDO_VTCXO28_EN_SEL,
    MT6353_LDO_VTCXO24_LP_MODE,
    MT6353_LDO_VTCXO24_EN,
    MT6353_LDO_VTCXO24_LP_CTRL,
    MT6353_LDO_VTCXO24_EN_CTRL,
    MT6353_LDO_VTCXO24_LP_SEL,
    MT6353_LDO_VTCXO24_EN_SEL,
    MT6353_LDO_VRF18_LP_MODE,
    MT6353_LDO_VRF18_EN,
    MT6353_LDO_VRF18_LP_CTRL,
    MT6353_LDO_VRF18_EN_CTRL,
    MT6353_LDO_VRF18_LP_SEL,
    MT6353_LDO_VRF18_EN_SEL,
    MT6353_LDO_VRF12_LP_MODE,
    MT6353_LDO_VRF12_EN,
    MT6353_LDO_VRF12_LP_CTRL,
    MT6353_LDO_VRF12_EN_CTRL,
    MT6353_LDO_VRF12_LP_SEL,
    MT6353_LDO_VRF12_EN_SEL,
    MT6353_LDO_VSIM1_LP_MODE,
    MT6353_LDO_VSIM1_EN,
    MT6353_LDO_VSIM1_LP_CTRL,
    MT6353_LDO_VSIM1_LP_SEL,
    MT6353_LDO_VSIM2_LP_MODE,
    MT6353_LDO_VSIM2_EN,
    MT6353_LDO_VSIM2_LP_CTRL,
    MT6353_LDO_VSIM2_LP_SEL,
    MT6353_RG_VSIM1_VOSEL,
    MT6353_RG_VSIM2_VOSEL,
    MT6353_AUXADC_ADC_OUT_CH7_BY_MD,
    MT6353_AUXADC_ADC_RDY_CH7_BY_MD,
    MT6353_AUXADC_RQST1_SET,
    MT6353_AUXADC_RQST1_CLR,
}PMIC6353_FLAGS_LIST_ENUM;

#endif // #ifdef PMIC_6353_REG_API
#endif // #ifndef __DCL_PMIC6353_SW_H_STRUCT__

