/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2015
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   cl1_timertype.h
 *
 *
 ******************************************************************************/

CL1_TIMER_TYPE(CTimerNone),
CL1_TIMER_TYPE(CTimerXL1IcsPilot),
CL1_TIMER_TYPE(CTimerXL1IcsSync),
CL1_TIMER_TYPE(CTimerXL1NsltPchOvhd),
CL1_TIMER_TYPE(CTimerXL1NsltInterMeas),
CL1_TIMER_TYPE(CTimerXL1AfltMeas),
CL1_TIMER_TYPE(CTimerXL1SltCci),
CL1_TIMER_TYPE(CTimerXL1SltQpch_1),
CL1_TIMER_TYPE(CTimerXL1SltQpch_2),
CL1_TIMER_TYPE(CTimerXL1SltPch),
CL1_TIMER_TYPE(CTimerXL1SltPchLostDet),
CL1_TIMER_TYPE(CTimerXL1SltnterMeas),
CL1_TIMER_TYPE(CTimerXL1ConnectPsRx),
CL1_TIMER_TYPE(CTimerXL1ConnectInterMeas),
CL1_TIMER_TYPE(CTimerXL1ConnectAfltMeas),
CL1_TIMER_TYPE(CTimerEvL1IcsPilot),
CL1_TIMER_TYPE(CTimerEvL1IcsSync),
CL1_TIMER_TYPE(CTimerEvL1NsltCC),
CL1_TIMER_TYPE(CTimerEvL1SltPch),
CL1_TIMER_TYPE(CTimerEvL1InterMeas),
CL1_TIMER_TYPE(CTimerEvL1ConnectRx),
CL1_TIMER_TYPE(CTimerEvL1ConnectInterMeas),
CL1_TIMER_TYPE(CTimerEvStdbyMeas),
CL1_TIMER_TYPE(CTimerEvStdbySync),
CL1_TIMER_TYPE(CTimerEvStdbyCgi),
CL1_TIMER_TYPE(CTimerEnd),
