/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*****************************************************************************
 *
 * Filename:
 * ---------
 *   md3_msgid.h
 *
 * Project:
 * --------
 *   
 *
 * Description:
 * ------------
 *   This file provides the msg id configuration.
 *
 * Author:
 * -------
 * -------
 *
 *============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * removed!
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *============================================================================
 ****************************************************************************/

#ifndef MD3_MSGID_H
#define MD3_MSGID_H

//do NOT use compile option in this file
//because compile option might be different among all MDs
//MD3 is C2K
    /* C2K_LTE_SAP */
    MSG_ID_C2K_LTE_RAT_CHANGE_REQ            ,
    MSG_ID_C2K_LTE_RAT_CHANGE_CNF            ,

    /* GMSS_CSS_SAP */
    MSG_ID_GMSS_CSS_MCC_SEARCH_REQ           ,
    MSG_ID_GMSS_CSS_MCC_SEARCH_CNF           ,
    MSG_ID_GMSS_CSS_SYS_ACQUIRE_REQ          ,
    MSG_ID_GMSS_CSS_SYS_ACQUIRE_CNF          ,
    MSG_ID_GMSS_CSS_CS_REG_REQ               ,
    MSG_ID_GMSS_CSS_CS_REG_CNF               ,
    MSG_ID_GMSS_CSS_PS_REG_REQ               ,
    MSG_ID_GMSS_CSS_PS_REG_CNF               ,
    MSG_ID_GMSS_CSS_DEACTIVATE_REQ           ,
    MSG_ID_GMSS_CSS_DEACTIVATE_CNF           ,
    MSG_ID_GMSS_CSS_RAT_CHANGE_REQ           ,
    MSG_ID_GMSS_CSS_READY_IND                ,
    MSG_ID_GMSS_CSS_NOT_READY_IND            ,
    MSG_ID_GMSS_CSS_SYS_LOST_IND             ,
    MSG_ID_GMSS_CSS_SYS_RECOVERY_IND         ,
    MSG_ID_GMSS_CSS_1X_CONN_STATUS_IND       ,
    MSG_ID_GMSS_CSS_MMSS_FILE_UPDATE_IND     ,
    MSG_ID_GMSS_CSS_PS_CHANGE_IND            ,
    MSG_ID_GMSS_CSS_PS_CONN_STATUS_IND       ,
    MSG_ID_GMSS_CSS_MCC_CHANGE_IND           ,
    MSG_ID_GMSS_CSS_PS_DEREG_REQ             ,
    MSG_ID_GMSS_CSS_ACTIVE_SIM_INFO_REQ      ,
    MSG_ID_GMSS_CSS_SUSPEND_STATUS_IND       ,
    MSG_ID_GMSS_CSS_SIM_PLMN_INFO_IND        ,
    MSG_ID_GMSS_CSS_PS_DEREG_CNF             ,
    MSG_ID_GMSS_CSS_SIM_PLMN_INFO_RSP        ,
    MSG_ID_GMSS_CSS_SET_RAT_MODE_REQ         ,
    MSG_ID_GMSS_CSS_MMSS_LIST_SYNC_REQ       ,
    MSG_ID_GMSS_CSS_CAMPING_INFO_IND         ,
    MSG_ID_GMSS_CSS_3GPP_NORMAL_SERVICE_REQ  ,
    //MSG_ID_GMSS_CSS_CELL_INFO_IND            ,  // move to tail to avoid MD3 build error

/* messages for VZW ECC call */
    MSG_ID_GMSS_CSS_EMC_SESSION_START_REQ    ,
    MSG_ID_GMSS_CSS_EMC_SESSION_STOP_REQ     ,
    MSG_ID_GMSS_CSS_EMC_LOCAL_DETACH_REQ     ,

    /* LTE_C2K_SAP */
    MSG_ID_LTE_C2K_RAT_CHANGE_REQ            ,
    MSG_ID_LTE_C2K_RAT_CHANGE_CNF            ,
    MSG_ID_LTE_C2K_IA_PDN_QUERY_REQ,
    MSG_ID_LTE_C2K_IA_PDN_QUERY_CNF,

    /* VAL_RAC_SAP */
    MSG_ID_VAL_RAC_RAT_CHANGE_START_REQ      ,
    MSG_ID_VAL_RAC_RAT_CHANGE_FINISH_REQ     ,
    MSG_ID_MD3_DEBUG_TRACE_IND,

    /* CLC_EAS_SAP */
    MSG_ID_CLC_EAS_EARFCN_LIST_UPDATE_REQ    ,

    /* C2K_LTE_SAP */
    MSG_ID_C2K_EL1_TXPWR_BACKOFF_INFO_IND    ,

    /* CSS_RSVAC_SAP */
    MSG_ID_CSS_RSVAC_FREQUENCY_SCAN_START_REQ,
    MSG_ID_CSS_RSVAC_FREQUENCY_SCAN_MODIFY_REQ,
    MSG_ID_CSS_RSVAC_FREQUENCY_SCAN_STOP_REQ,
    MSG_ID_RSVAC_CSS_FREQUENCY_SCAN_ACCEPT_IND,
    MSG_ID_RSVAC_CSS_FREQUENCY_SCAN_PREEMPT_IND,
    
    /* PSW_RSVAS_SAP */
    MSG_ID_RSVAS_CAS_SERVICE_RES_OCCUPY_IND,
    MSG_ID_RSVAS_CAS_SUSPEND_SERVICE_REQ,
    MSG_ID_RSVAS_CAS_SUSPEND_SERVICE_CNF,
    MSG_ID_RSVAS_CAS_RESUME_SERVICE_REQ,
    MSG_ID_RSVAS_CAS_ABORT_SERVICE_REQ,
    MSG_ID_RSVAS_CAS_ABORT_SERVICE_CNF,
    MSG_ID_RSVAS_CAS_ABORT_SERVICE_COMPLETE_IND,
    MSG_ID_RSVAS_CAS_VIRTUAL_SUSPEND_SERVICE_REQ,
    MSG_ID_RSVAS_CAS_VIRTUAL_SUSPEND_SERVICE_CNF,
    MSG_ID_RSVAS_CAS_VIRTUAL_SUSPEND_SERVICE_COMPLETE_IND,
    MSG_ID_RSVAS_CAS_VIRTUAL_RESUME_SERVICE_REQ,
    MSG_ID_RSVAS_CAS_PROTECT_CS_SERVICE_REQ,

    /* CLC_ERRC_SAP */
    MSG_ID_CAS_EAS_LTE_MEASUREMENT_CNF,
    MSG_ID_CAS_EAS_LTE_MEASUREMENT_IND,
    MSG_ID_CAS_EAS_EVALUATE_ECELL_CNF,
    MSG_ID_CAS_EAS_EVALUATE_ECELL_STOP_CNF,
    MSG_ID_CAS_EAS_ACTIVATE_ECELL_CNF,
    MSG_ID_EAS_CAS_CONFIG_CCELL_MEAS_REQ,
    MSG_ID_EAS_CAS_REPORT_CGI_REQ,
    MSG_ID_EAS_CAS_ACTIVATE_CCELL_REQ,
    MSG_ID_EAS_CAS_PARAM_UPDATE_IND,

    /* MRS_CSS_SAP */
    MSG_ID_MRS_CAS_LOWER_LAYER_AVAILABILITY_UPDATE_IND,

 /*[20150629 Ali] SRLTE: CL1_LL1 use */
    MSG_ID_CL1_LL1_RAT_STATUS_IND,
    MSG_ID_CL1_LL1_MODE_STATUS_IND,
    MSG_ID_LL1_CL1_MODE_STATUS_UPDATE_IND,
    MSG_ID_CL1_LL1_ACTIVE_MEASURE_STATUS_IND,
    MSG_ID_CL1_LL1_MEASURE_REQ,
    MSG_ID_CL1_LL1_STANDBY_MEASURE_DONE_IND,
    MSG_ID_LL1_CL1_GAP_SERVICE_REQ,
    MSG_ID_CL1_LL1_GAP_STOP_REQ,
    MSG_ID_LL1_CL1_GAP_STOP_CNF,
    MSG_ID_LL1_CL1_GAP_STOP_REQ,
    MSG_ID_CL1_LL1_GAP_STOP_CNF,
    MSG_ID_LL1_CL1_GAP_SUSPEND_REQ,
    MSG_ID_CL1_LL1_GAP_SUSPEND_CNF,
    MSG_ID_LL1_CL1_GAP_RESUME_IND,
    MSG_ID_CL1_LL1_AUTO_GAP_REQ,
    MSG_ID_LL1_CL1_AUTO_GAP_CNF,
    MSG_ID_LL1_CL1_AUTO_GAP_STOP_IND,
    MSG_ID_CL1_LL1_AUTO_GAP_STOP_RES,
    MSG_ID_CL1_LL1_AUTO_GAP_END_IND,
    MSG_ID_LL1_CL1_AUTO_GAP_AVAILABLE_IND,
    MSG_ID_LL1_CL1_AUTO_GAP_UNAVAILABLE_IND,
    MSG_ID_LL1_CL1_GAP_NOTIFY_IND,
    MSG_ID_CL1_LL1_GAP_PATTERN_IND,

    /* PSW_L4C_SAP */
    MSG_ID_C2K_LTE_CSFB_REQ,
    MSG_ID_C2K_LTE_CSFB_CNF,
    MSG_ID_C2K_LTE_CSFB_STOP_REQ,
    MSG_ID_C2K_LTE_CSFB_STOP_CNF,

    MSG_ID_L4C_C2K_EFUN_STATE_IND,

    /* VDM_VAL_SAP */
    MSG_ID_VDM_VAL_SEND_DCN_REQ,
    MSG_ID_VDM_VAL_SEND_DCN_START_IND,
    MSG_ID_VDM_VAL_SEND_DCN_START_RSP,
    MSG_ID_VDM_VAL_SEND_DCN_END_IND,
    MSG_ID_VDM_VAL_IMS_REG_STATUS_IND,

    /*Message for 3GPP2 SMS*/
    MSG_ID_SDM_VAL_C2K_SMS_SEND_REQ,
    MSG_ID_SDM_VAL_C2K_SMS_SEND_CNF,

    /* new Message for GMSS_CSS_SAP */
    MSG_ID_GMSS_CSS_CELL_INFO_IND,

    /* CLC_ERRC_SAP */
    MSG_ID_EAS_CAS_LTE_POWER_ON_IND,
    MSG_ID_EAS_CAS_LTE_POWER_OFF_IND,

    MSG_ID_L4C_C2K_PWROFF_START_IND,

    MSG_ID_UIM_SIM_MDSTATUS_UPDATE_IND,
    MSG_ID_L4C_VAL_MDSTATUS_FLOW_VERSION_IND,
    MSG_ID_CL1_LL1_SIB8_TIMING_SYNC_REQ,
    MSG_ID_LL1_CL1_SIB8_TIMING_SYNC_CNF,

    MSG_ID_L4C_C2K_IMS_REG_STATUS_UPDATE_IND,

    MSG_ID_GMSS_CSS_MSPL_SEARCH_EXHAUSTED,
    MSG_ID_ERRC_CLC_LTE_SCAN_C2K_ACTIVE_PARAMS_IND,

	/* TC01 3GPP2 SMS over IMS */
    MSG_ID_SDM_VAL_C2K_SMS_IND,
    MSG_ID_SDM_VAL_C2K_SMS_RSP,
    MSG_ID_IMCSMS_VAL_C2K_SMS_SEND_REQ,
    MSG_ID_IMCSMS_VAL_C2K_SMS_SEND_CNF,
    
    MSG_ID_UIM_SIM_C2K_BATCH_FILE_READ_CNF,
	
	/* inform MD3 of the current MD is TK or BSP */
	MSG_ID_L4C_VAL_MDSTATUS_TK_BSP_IND,

    MSG_ID_GMSS_CSS_CS_SUSPEND_IND,
    MSG_ID_GMSS_CSS_CS_RESUME_REQ,

    /* MD3 inform MD1 about roaming status*/
    MSG_ID_L4C_C2K_ROAMING_SETTING_SYNC_REQ,

    MSG_ID_GMSS_CSS_SET_RAT_MODE_CNF,
    MSG_ID_GMSS_CSS_C2K_SERVICE_IND,
    
    MSG_ID_L4C_C2K_1X_LOOP_BACK_CALL_REQ,
    MSG_ID_L4C_C2K_1X_LOOP_BACK_CALL_CNF,    
    
	MSG_ID_L4C_C2K_TXRX_ACTIVE_TIME_REQ,
    MSG_ID_L4C_C2K_TXRX_ACTIVE_TIME_CNF,

    MSG_ID_C2K_LTE_PDN_CONTEXT_TRANSFER_REQ  ,
    MSG_ID_C2K_LTE_PDN_CONTEXT_TRANSFER_CNF  ,

    MSG_ID_LTE_C2K_PDN_CONTEXT_TRANSFER_REQ,
    MSG_ID_LTE_C2K_PDN_CONTEXT_TRANSFER_CNF,

    /* C2K MT SMS from IMS, need sent to MD3 */
    MSG_ID_IMCSMS_VAL_C2K_SMS_RECV_REQ,
    MSG_ID_IMCSMS_VAL_C2K_SMS_RECV_CNF,

    MSG_ID_L4C_C2K_CS_STATUS_IND,

	MSG_ID_L4C_C2K_POWER_OFF_REQ,
	MSG_ID_L4C_C2K_POWER_OFF_CNF,

    MSG_ID_L4C_C2K_RF_OFF_REQ,
    MSG_ID_L4C_C2K_RF_OFF_CNF,
    
    /* CL1_RSVAS_SAP */
    MSG_ID_RSVAS_CL1_LL1_SUSPEND_IND,
    MSG_ID_RSVAS_CL1_LL1_RESUME_IND,
    MSG_ID_RSVAS_CL1_LL1_VIRTUAL_RESUME_IND,

    /* Sent to MOD_CVAL from SMU */
    MSG_ID_SMU_CVAL_CARRIER_RESTRICTION_STATUS_IND,
    MSG_ID_SMU_CVAL_CARRIER_RESTRICTION_SYNC_IND,
    /* MD3 CVAL to SMU */
    MSG_ID_CVAL_SMU_CARRIER_RESTRICTION_STATUS_IND,

#endif /* MD3_MSGID_H */
